//查询单个ES文档数据
GET http://localhost:9200/books/_doc/42
Accept: application/json

###
//查询所有ES文档数据
GET http://localhost:9200/books/_search
Accept: application/json

###
//按条件查询ES文档数据
GET http://localhost:9200/books/_search?q=name:spring
Accept: application/json

###
POST http://localhost:9200/books/_doc/42
Content-Type: application/json

{"type":"spring",     "name":"spring2",     "description":"spring3"}

###

