server:
  port: 80 #指定访问端口

spring:
  datasource: #数据源连接参数
    druid:
      # mysql数据源
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm?serverTimezone=UTC
      username: root
      password: root
  #消息队列技术
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order
#  activemq:
#    broker-url: tcp://localhost:61616
#  rabbitmq:
#    host: localhost
#    port: 5672
rocketmq:
  name-server: localhost:9876
  producer:
    group: group_rocketmq

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印MP日志,上线时关闭该配置
  global-config:
    db-config:
      id-type: auto #全局默认主键类型
      #table-prefix: tb_ #表名前缀，数据库表名与实体类名不一致时采用

#自定义配置
#1.测试用例生成随机数据
testcase:
  book:
    #    id: ${random.int()}
    type: ${random.value}
    name: ${random.value}
    description: ${random.value}

---


